### ISSUE TITLE
win下使用虚拟路径报错 Middleware meta not found

### ISSUE THREAD

**Issue by MrLanYX** [MrSmallLiu/pkg-egg-example#4]
window下使用虚拟路径下的依赖报错提示
```
2022-01-12 16:28:52,844 ERROR 696 nodejs.TypeError: Middleware meta not found
    at AppWorkerLoader.loadMiddleware (C:\snapshot\src\node_modules\egg-core\lib\loader\mixin\middleware.js:66:15)
    at AppWorkerLoader.load (C:\snapshot\src\node_modules\egg\lib\loader\app_worker_loader.js:39:10)
    at new Application (C:\snapshot\src\node_modules\egg\lib\application.js:66:19)
    at Object.<anonymous> (C:\snapshot\src\node_modules\egg-cluster\lib\app_worker.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (pkg/prelude/bootstrap.js:1801:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)

pid: 696
```
但如果使用项目根目录 `pkg-egg-example\src` 就能够正常启动

**Comment by pxim** [comment]
同样的错误，以前一直没问题，今天发布pkg就出现这个问题了
